name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: --privileged
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Docker Compose CLI (optional)
        run: |
          docker compose version

      - name: Start DB container
        run: |
          docker compose -f docker-compose-test.yml up -d littleneighbors_db

      - name: Wait for DB to be ready
        run: |
          bash docker/wait-for-it.sh localhost:3306 --timeout=30 --strict -- echo "DB lista"

      - name: Run tests
        run: |
          docker compose -f docker-compose-test.yml run --rm littleneighbors_tests

      - name: Shutdown containers
        run: |
          docker compose -f docker-compose-test.yml down

