name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: littleneighbors
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=2s --health-retries=10
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make wait-for-it.sh executable
        run: chmod +x docker/wait-for-it.sh

      - name: Wait for DB to be ready
        run: ./docker/wait-for-it.sh 127.0.0.1:3306 --timeout=30 --strict -- echo "DB lista"

      - name: Run tests
        run: mvn clean test -B



