name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: littleneighbors
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=2s --health-retries=10
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Build and run tests
        run: |
          docker compose -f docker-compose-test.yml build
          docker compose -f docker-compose-test.yml run --rm littleneighbors_tests
      - name: Shutdown containers
        run: docker compose -f docker-compose-test.yml down





